ORIGINAL='analog_to_original';REAL='real_place_reconstruction'
CASES=[
 ('original_crew','Build an original crew habitat.',ORIGINAL),
 ('scifi_crew','Build a sci-fi crew habitat.',ORIGINAL),
 ('hyphen_crew','Build a crew-habitat.',ORIGINAL),
 ('crewed','Create a crewed habitat.',ORIGINAL),
 ('mars_habitat','Build a Mars habitat.',ORIGINAL),
 ('mars_crew','Build a Mars crew habitat.',ORIGINAL),
 ('martian_crew','Build a Martian crew habitat.',ORIGINAL),
 ('mars_hyphen','Build an original Mars crew-habitat.',ORIGINAL),
 ('polite','Can you build an original crew habitat?',ORIGINAL),
 ('please','Please make a crew habitat.',ORIGINAL),
 ('scifi_mars','Build a sci-fi Mars crew habitat.',ORIGINAL),
 ('lunar','Build an original lunar crew habitat.',ORIGINAL),
 ('on_mars','Build an original crew habitat on Mars.',ORIGINAL),
 ('functional_rooms','Build an original crew habitat with a galley and laboratory.',ORIGINAL),
 ('six_people','Build a crew habitat for six people.',ORIGINAL),
 ('no_weapons','Build a crew habitat with no weapons.',ORIGINAL),
 ('analogy','Build an original crew habitat inspired by CHAPEA.',ORIGINAL),
 ('excluded_replica','Build a crew habitat, not a replica of CHAPEA.',ORIGINAL),
 ('generic_prior','Build an original habitat.',ORIGINAL),
 ('mars_prior','Build an original Mars base.',ORIGINAL),
 ('named_article','Build the CHAPEA crew habitat.',REAL),
 ('named_first','Build a CHAPEA crew habitat.',REAL),
 ('named_trailing','Build an original crew habitat CHAPEA.',REAL),
 ('named_called','Build a Mars crew habitat called CHAPEA.',REAL),
 ('named_of','Build an original crew habitat of CHAPEA.',REAL),
 ('actual','Build the actual crew habitat.',REAL),
 ('at_location','Build an original crew habitat at Johnson Space Center.',REAL),
 ('inside_location','Build an original crew habitat inside the NASA facility.',REAL),
 ('recreate','Build a crew habitat; recreate the CHAPEA layout.',REAL),
 ('copy','Create a crew habitat as an exact copy of CHAPEA.',REAL),
 ('retain','Build a crew habitat but retain the actual dimensions.',REAL),
 ('negated_original','Build a crew habitat, not an original design.',REAL),
 ('research_crew','Research a crew habitat.',REAL),
 ('research_actual','Research NASA CHAPEA crew habitat floor plans.',REAL),
 ('named_reference_first','Build the Louvre, inspired by an original crew habitat.',REAL),
 ('unknown_prefix','Build an original premium crew habitat.',REAL),
 ('unrelated_crew_kind','Build an original crew museum.',REAL),
 ('negated_request','Do not build an original crew habitat.',None),
 ('deferred_request','Build an original crew habitat after I get home.',None),
 ('planning_request','Plan an original crew habitat.',None),
 ('question','Can this build a Mars crew habitat?',None),
 ('quoted_command','The note says "Build an original crew habitat."',None),
 ('edit_request','Create a new crew habitat in my current world.',None),
]
