"""CPU synthetic source/trim/recovery tests; no owner worlds, UI or models."""
from pathlib import Path
import hashlib,json,os,shutil,subprocess,sys,tempfile
H=Path(__file__).resolve().parent;names=('world-observation-exclusion-055','world-observation-trim-056')
node=os.environ.get('KIRA_TEST_NODE') or shutil.which('node') or 'C:/Program Files/nodejs/node.exe'
results=[]
with tempfile.TemporaryDirectory(prefix='world056-public-') as temp:
 root=Path(temp);assert root.parent.resolve()==Path(tempfile.gettempdir()).resolve()
 for name in names:
  source=H.parent/name;dest=root/name;dest.mkdir()
  for part in ('candidate','baseline'):
   if (source/part).exists():shutil.copytree(source/part,dest/part)
  (dest/'fixtures').mkdir()
  if name.endswith('055'):
   shutil.copyfile(source/'fixtures/synthetic-habitat.json',dest/'fixtures/synthetic-habitat.json')
   shutil.copyfile(source/'test_setting.py',dest/'test_setting.py')
  else:
   shutil.copyfile(source/'fixtures/supported-layouts.json',dest/'fixtures/supported-layouts.json')
   shutil.copyfile(source/'test_trim.mjs',dest/'test_trim.mjs')
   nsource=source/'native-successor-001';ndest=dest/'native-successor-001'
   shutil.copytree(nsource/'candidate',ndest/'candidate');shutil.copyfile(nsource/'CANDIDATE-CLOSURE.json',ndest/'CANDIDATE-CLOSURE.json')
   (ndest/'installation').mkdir()
   for script in ('test_installer.py','install_exact.py'):shutil.copyfile(nsource/'installation'/script,ndest/'installation'/script)
 commands=[(names[0],[sys.executable,'-B','test_setting.py','--synthetic-only']),
           (names[1],[node,'test_trim.mjs']),
           (names[1]+'/native-successor-001',[sys.executable,'-B','installation/test_installer.py'])]
 for package,cmd in commands:
  run=subprocess.run(cmd,cwd=root/package,capture_output=True,text=True,timeout=20,env={**os.environ,'PYTHONDONTWRITEBYTECODE':'1'})
  if run.returncode:raise RuntimeError(package+' '+run.stdout+run.stderr)
  results.append({'package':package,'result':json.loads(run.stdout)})
 # 055 regenerates the complete pair of synthetic supported layouts.
 a=(root/names[0]/'fixtures/supported-layouts.json').read_bytes();b=(root/names[1]/'fixtures/supported-layouts.json').read_bytes()
 assert a==b,'The trim test must use the exact synthetic fixture generated by source tests'
 print(json.dumps({'status':'PUBLIC056_SYNTHETIC_CLOSURE_PASS','results':results,'synthetic_fixture_sha256':hashlib.sha256(a).hexdigest(),
  'owner_data_reads_writes':0,'models_GPU_UI_servers_exports':0,'native_visual_or_owner_approval':False}))
