#!/usr/bin/env python3
"""Build or verify the deterministic private handoff file inventory."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import sys
from typing import Any


MANIFEST_NAME = "HANDOFF_MANIFEST.json"
CHECKSUM_NAME = "HANDOFF_SHA256SUMS.txt"
EXCLUDED_PARTS = {".git", "__pycache__", "local_data", ".venv", "venv"}
EXCLUDED_SUFFIXES = {".pyc", ".pyo"}
MAX_FILE_BYTES = 50 * 1024 * 1024


def _classification(relative: str) -> str:
    path = relative.replace("\\", "/")
    if path.startswith("voice_packs/") and path.lower().endswith(".wav"):
        return "private_biometric_named_reviewers_only"
    if path.startswith("voice_packs/"):
        return "private_voice_policy_or_profile"
    if path.startswith("memory_exports/"):
        return "private_reviewed_continuity"
    if path.startswith("mind_v21_static/"):
        return "static_mind_acceptance_evidence"
    if path.startswith("static_body_review/"):
        return "static_body_data_only"
    if path.startswith("portable_runtime/"):
        return "portable_runtime_source_or_docs"
    if path.startswith("evaluation/"):
        return "isolated_evaluator_source_or_docs"
    if path.startswith("tools/"):
        return "handoff_validator_or_build_source"
    return "handoff_documentation_or_policy"


def _inventory(root: Path) -> list[dict[str, Any]]:
    entries: list[dict[str, Any]] = []
    for path in sorted(root.rglob("*"), key=lambda item: item.relative_to(root).as_posix()):
        relative_path = path.relative_to(root)
        relative = relative_path.as_posix()
        if relative in {MANIFEST_NAME, CHECKSUM_NAME}:
            continue
        if any(part in EXCLUDED_PARTS or part.startswith(".venv") for part in relative_path.parts):
            raise ValueError(f"excluded generated/private directory present: {relative}")
        if path.is_symlink():
            raise ValueError(f"symbolic links are not allowed: {relative}")
        if path.is_dir():
            continue
        if path.suffix.lower() in EXCLUDED_SUFFIXES:
            raise ValueError(f"generated bytecode is not allowed: {relative}")
        size = path.stat().st_size
        if size > MAX_FILE_BYTES:
            raise ValueError(f"file exceeds 50 MiB handoff limit: {relative}")
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        entries.append(
            {
                "path": relative,
                "bytes": size,
                "sha256": digest,
                "classification": _classification(relative),
            }
        )
    return entries


def _root(entries: list[dict[str, Any]]) -> tuple[int, str]:
    preimage = "".join(
        f"{entry['path']}\0{entry['bytes']}\0{entry['sha256']}\n" for entry in entries
    ).encode("utf-8")
    return len(preimage), hashlib.sha256(preimage).hexdigest()


def _render(root: Path) -> tuple[bytes, bytes]:
    entries = _inventory(root)
    preimage_bytes, root_sha = _root(entries)
    manifest = {
        "schema": "kira-world-private-hanson-handoff-manifest/v1",
        "scope": "private_named_hanson_review_only",
        "public_release_allowed": False,
        "onward_redistribution_allowed": False,
        "entry_count": len(entries),
        "total_entry_bytes": sum(entry["bytes"] for entry in entries),
        "root_preimage_bytes": preimage_bytes,
        "root_sha256": root_sha,
        "entries": entries,
        "claim_boundary": (
            "File identity and classification inventory only; not a GO, runtime, "
            "personhood, consciousness, robot-safety, or legal-rights decision."
        ),
    }
    manifest_bytes = (
        json.dumps(manifest, indent=2, ensure_ascii=False, sort_keys=False) + "\n"
    ).encode("utf-8")
    checksums = "".join(
        f"{entry['sha256']}  {entry['path']}\n" for entry in entries
    ).encode("utf-8")
    return manifest_bytes, checksums


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    root = args.root.resolve(strict=True)
    manifest_bytes, checksum_bytes = _render(root)
    manifest_path = root / MANIFEST_NAME
    checksum_path = root / CHECKSUM_NAME
    if args.write:
        manifest_path.write_bytes(manifest_bytes)
        checksum_path.write_bytes(checksum_bytes)
        print(f"HANDOFF_MANIFEST_WRITTEN entries={len(json.loads(manifest_bytes)['entries'])}")
        return 0
    if not manifest_path.is_file() or manifest_path.read_bytes() != manifest_bytes:
        print("HANDOFF_MANIFEST_MISMATCH", file=sys.stderr)
        return 1
    if not checksum_path.is_file() or checksum_path.read_bytes() != checksum_bytes:
        print("HANDOFF_SHA256SUMS_MISMATCH", file=sys.stderr)
        return 1
    parsed = json.loads(manifest_bytes)
    print(
        f"HANDOFF_MANIFEST_PASS entries={parsed['entry_count']} "
        f"root_sha256={parsed['root_sha256']}"
    )
    return 0


if __name__ == "__main__":
    sys.dont_write_bytecode = True
    raise SystemExit(main())
