import fs from 'node:fs';
import assert from 'node:assert/strict';
import {installCpuCanvas} from './cpu_canvas.mjs';
import {buildAuthoredScene} from './authored_scene.mjs';
const req=JSON.parse(fs.readFileSync(0,'utf8'));
assert.throws(()=>installCpuCanvas(req.canvasModule,[]),/Explicit regular/);
const missing=req.fontPaths.map(v=>[...v]);missing[0][0]+='.intentionally_missing';
assert.throws(()=>installCpuCanvas(req.canvasModule,missing),/font file is missing/);
const {canvasFactory}=installCpuCanvas(req.canvasModule,req.fontPaths);
assert.throws(()=>buildAuthoredScene(req.geometry,req.metadata,()=>null),/Missing authored screen map/);
assert.throws(()=>globalThis.fetch('https://example.invalid/'),/External fetch rejected/);
const fixture=buildAuthoredScene(req.geometry,req.metadata,canvasFactory);
assert.equal(fixture.semantic.size,141);
const c=canvasFactory();assert.equal(c.data,undefined,'Native data() must not misidentify Canvas as DataTexture');c.width=c.height=2;const ctx=c.getContext('2d');ctx.fillStyle='#ee2211';ctx.fillRect(0,0,2,2);
assert.equal(ctx.getImageData(0,0,2,2).data[3],255);
assert.ok((await new Promise(resolve=>c.toBlob(resolve,'image/png'))).size>60);
const sidecar=structuredClone(req.metadata);sidecar.colliders[0].owner_node_id='node:missing_owner';
assert.throws(()=>buildAuthoredScene(req.geometry,sidecar,canvasFactory),/Unmapped collider owner/);
process.stdout.write(JSON.stringify({status:'CPU_CONTRACT_CHECKS_PASS',checks:['required_fonts_explicit','missing_font_rejected','missing_canvas_maps_rejected','external_fetch_rejected','native_canvas_data_method_hidden','nontransparent_png_available','missing_collider_owner_rejected']}));
