#!/usr/bin/env python3
"""Run the sealed Mind V21 author tests from a short, disposable path.

The historical author test intentionally retains its original sibling-relative
V19/V20 layout.  This wrapper leaves every sealed file unchanged, verifies the
two packaged predecessor schemas by byte count and SHA-256, recreates that
legacy layout below a short temporary root, and runs the unchanged test there.
"""

from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
from typing import Any


HERE = Path(__file__).resolve().parent
AUTHOR_SOURCE = HERE / "author"
DEPENDENCY_SOURCE = HERE / "deps"

EXPECTED_TEST_RESULT = {
    "status": "AUTHOR_TESTS_PASS",
    "round_count": 2,
    "tests_per_round": 64,
    "total_tests_run": 128,
    "candidate_false_accept_count": 0,
}

DEPENDENCIES = (
    {
        "package_path": DEPENDENCY_SOURCE / "v19_schema.json",
        "legacy_directory": (
            "kira_conversation_continuity_v19_recursive_receipt_proof_verifier_"
            "schema_closure_data_only_author_source"
        ),
        "legacy_filename": "RECURSIVELY_CLOSED_SCHEMAS_V19.json",
        "bytes": 33_788,
        "sha256": "ed2e2367a5a942b65a9a6107114e7c5a93b323b37e981c35a5d94e5359601dba",
    },
    {
        "package_path": DEPENDENCY_SOURCE / "v20_schema.json",
        "legacy_directory": (
            "kira_conversation_continuity_v20_authoritative_journal_fixed_key_"
            "roles_data_only_author_source"
        ),
        "legacy_filename": "AUTHORITATIVE_JOURNAL_AND_FIXED_ROLE_SCHEMAS_V20.json",
        "bytes": 42_299,
        "sha256": "82417f2634e14b6f49dfc6414364ede41f23c053d4b55fee1723fb168c27e53b",
    },
)


class PortableAuthorTestError(RuntimeError):
    """A fail-closed portable-test precondition or result failed."""


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _verify_regular_file(path: Path, expected_bytes: int, expected_sha256: str) -> None:
    if path.is_symlink() or not path.is_file():
        raise PortableAuthorTestError(f"required regular file is missing: {path}")
    actual_bytes = path.stat().st_size
    actual_sha256 = _sha256(path)
    if actual_bytes != expected_bytes or actual_sha256 != expected_sha256:
        raise PortableAuthorTestError(
            "dependency identity mismatch: "
            f"{path} expected={expected_bytes}/{expected_sha256} "
            f"actual={actual_bytes}/{actual_sha256}"
        )


def _tree_snapshot(root: Path) -> dict[str, tuple[int, str]]:
    if root.is_symlink() or not root.is_dir():
        raise PortableAuthorTestError(f"required source directory is missing: {root}")
    snapshot: dict[str, tuple[int, str]] = {}
    for path in sorted(root.rglob("*"), key=lambda item: item.relative_to(root).as_posix()):
        relative = path.relative_to(root).as_posix()
        if path.is_symlink():
            raise PortableAuthorTestError(f"symbolic links are not allowed: {relative}")
        if path.is_dir():
            if path.name == "__pycache__":
                raise PortableAuthorTestError(f"generated bytecode directory is not allowed: {relative}")
            continue
        if not path.is_file():
            raise PortableAuthorTestError(f"non-regular author-tree entry: {relative}")
        if path.suffix.lower() in {".pyc", ".pyo"}:
            raise PortableAuthorTestError(f"generated bytecode is not allowed: {relative}")
        snapshot[relative] = (path.stat().st_size, _sha256(path))
    if "test_mind_v21_author.py" not in snapshot:
        raise PortableAuthorTestError("sealed author test is missing")
    return snapshot


def _parse_result(stdout: str) -> dict[str, Any]:
    lines = [line.strip() for line in stdout.splitlines() if line.strip()]
    if not lines:
        raise PortableAuthorTestError("author test emitted no machine-readable result")
    try:
        result = json.loads(lines[-1])
    except json.JSONDecodeError as exc:
        raise PortableAuthorTestError("author test result is not valid JSON") from exc
    if not isinstance(result, dict):
        raise PortableAuthorTestError("author test result must be a JSON object")
    for key, expected in EXPECTED_TEST_RESULT.items():
        if result.get(key) != expected:
            raise PortableAuthorTestError(
                f"author test result mismatch for {key}: expected {expected!r}, "
                f"found {result.get(key)!r}"
            )
    rounds = result.get("rounds")
    if not isinstance(rounds, list) or len(rounds) != 2:
        raise PortableAuthorTestError("author test must report exactly two rounds")
    for index, round_result in enumerate(rounds, start=1):
        if not isinstance(round_result, dict):
            raise PortableAuthorTestError(f"author test round {index} is malformed")
        if (
            round_result.get("tests_run") != 64
            or round_result.get("failures") != 0
            or round_result.get("errors") != 0
            or round_result.get("successful") is not True
        ):
            raise PortableAuthorTestError(f"author test round {index} did not pass 64/64")
    return result


def run() -> dict[str, Any]:
    source_snapshot = _tree_snapshot(AUTHOR_SOURCE)
    for dependency in DEPENDENCIES:
        _verify_regular_file(
            dependency["package_path"],
            dependency["bytes"],
            dependency["sha256"],
        )

    temp_parent = Path(tempfile.gettempdir()).resolve()
    temporary_path: Path | None = None
    result: dict[str, Any]
    with tempfile.TemporaryDirectory(prefix="v21p-", dir=temp_parent) as temporary:
        temporary_path = Path(temporary).resolve()
        if temporary_path.parent != temp_parent:
            raise PortableAuthorTestError("temporary root escaped the system temporary directory")

        legacy_root = temporary_path / "m"
        shadow_author = legacy_root / "author"
        shutil.copytree(AUTHOR_SOURCE, shadow_author)
        if _tree_snapshot(shadow_author) != source_snapshot:
            raise PortableAuthorTestError("sealed author tree changed during the portable copy")

        for dependency in DEPENDENCIES:
            destination_directory = legacy_root / dependency["legacy_directory"]
            destination_directory.mkdir(parents=True, exist_ok=False)
            destination = destination_directory / dependency["legacy_filename"]
            shutil.copy2(dependency["package_path"], destination)
            _verify_regular_file(destination, dependency["bytes"], dependency["sha256"])

        if os.name == "nt":
            longest = max(
                len(str(legacy_root / item["legacy_directory"] / item["legacy_filename"]))
                for item in DEPENDENCIES
            )
            if longest >= 248:
                raise PortableAuthorTestError(
                    f"temporary legacy path is too long for reliable Windows access: {longest}"
                )

        environment = os.environ.copy()
        environment["PYTHONDONTWRITEBYTECODE"] = "1"
        environment["PYTHONWARNINGS"] = "error"
        command = [sys.executable, "-B", "-W", "error", "test_mind_v21_author.py"]
        completed = subprocess.run(
            command,
            cwd=shadow_author,
            env=environment,
            stdin=subprocess.DEVNULL,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            encoding="utf-8",
            errors="strict",
            check=False,
        )
        if completed.stderr:
            sys.stderr.write(completed.stderr)
        if completed.stdout:
            sys.stdout.write(completed.stdout)
        if completed.returncode != 0:
            raise PortableAuthorTestError(
                f"unchanged author test exited with status {completed.returncode}"
            )
        result = _parse_result(completed.stdout)

        if _tree_snapshot(shadow_author) != source_snapshot:
            raise PortableAuthorTestError("author test mutated its disposable sealed-tree copy")
        if _tree_snapshot(AUTHOR_SOURCE) != source_snapshot:
            raise PortableAuthorTestError("author test mutated the packaged sealed author tree")

    if temporary_path is None or temporary_path.exists():
        raise PortableAuthorTestError("temporary author-test root was not removed")
    return result


def main() -> int:
    try:
        result = run()
    except (OSError, PortableAuthorTestError, subprocess.SubprocessError) as exc:
        print(f"V21_PORTABLE_AUTHOR_TEST FAIL: {exc}", file=sys.stderr)
        return 1
    print(
        "V21_PORTABLE_AUTHOR_TEST PASS "
        f"tests={result['total_tests_run']}/{result['total_tests_run']} "
        "dependency_hashes=verified sealed_author_unchanged=true temp_cleanup=verified"
    )
    return 0


if __name__ == "__main__":
    sys.dont_write_bytecode = True
    raise SystemExit(main())
